name       : python-send2trash
version    : 1.8.0
release    : 5
source     :
    - https://github.com/arsenetar/send2trash/archive/refs/tags/1.8.0.tar.gz : 937b038abd9f1e7b8c5d7a116be5dc4663beb71df74dcccffe56cacf992c7a9c
license    : BSD-3-Clause
component  : programming.python
summary    : Send file to trash natively under Mac OS X, Windows and Linux
description: |
    Send2Trash is a small package that sends files to the Trash (or Recycle Bin) natively and on all platforms. On OS X, it uses native FSMoveObjectToTrashSync Cocoa calls, on Windows, it uses native (and ugly) SHFileOperation win32 calls. On other platforms, if PyGObject and GIO are available, it will use this. Otherwise, it will fallback to itsZ own implementation of the trash specifications from freedesktop.org.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
