name       : python-send2trash
version    : 1.8.2
release    : 7
source     :
    - https://github.com/arsenetar/send2trash/archive/refs/tags/1.8.2.tar.gz : 0fc5e578a8f5c34455dd76e26909e73ea61250d796d23e36804999d4318cd5c2
homepage   : https://github.com/arsenetar/send2trash
license    : BSD-3-Clause
component  : programming.python
summary    : Send file to trash natively under Mac OS X, Windows and Linux
description: |
    Send2Trash is a small package that sends files to the Trash (or Recycle Bin) natively and on all platforms. On OS X, it uses native FSMoveObjectToTrashSync Cocoa calls, on Windows, it uses native (and ugly) SHFileOperation win32 calls. On other platforms, if PyGObject and GIO are available, it will use this. Otherwise, it will fallback to itsZ own implementation of the trash specifications from freedesktop.org.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
